//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s32.Sceh.WinApp.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Buttons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Buttons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("s32.Sceh.WinApp.Translations.Buttons", typeof(Buttons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string BoldText {
            get {
                return ResourceManager.GetString("BoldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find cards or games.
        /// </summary>
        public static string FindCards {
            get {
                return ResourceManager.GetString("FindCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string ItalicText {
            get {
                return ResourceManager.GetString("ItalicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open page.
        /// </summary>
        public static string OpenPage {
            get {
                return ResourceManager.GetString("OpenPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste all selected cards.
        /// </summary>
        public static string PasteAllCards {
            get {
                return ResourceManager.GetString("PasteAllCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste date.
        /// </summary>
        public static string PasteDate {
            get {
                return ResourceManager.GetString("PasteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste my selected cards.
        /// </summary>
        public static string PasteMyCards {
            get {
                return ResourceManager.GetString("PasteMyCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste other selected cards.
        /// </summary>
        public static string PasteOtherCards {
            get {
                return ResourceManager.GetString("PasteOtherCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score down -1.
        /// </summary>
        public static string ScoreDown {
            get {
                return ResourceManager.GetString("ScoreDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score up +1.
        /// </summary>
        public static string ScoreUp {
            get {
                return ResourceManager.GetString("ScoreUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all cards.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show duplicated cards for trade.
        /// </summary>
        public static string ShowDuplicates {
            get {
                return ResourceManager.GetString("ShowDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my cards.
        /// </summary>
        public static string ShowMyCards {
            get {
                return ResourceManager.GetString("ShowMyCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only selected cards.
        /// </summary>
        public static string ShowOnlySelected {
            get {
                return ResourceManager.GetString("ShowOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show his cards.
        /// </summary>
        public static string ShowOtherCards {
            get {
                return ResourceManager.GetString("ShowOtherCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show selected games.
        /// </summary>
        public static string ShowSelectedApp {
            get {
                return ResourceManager.GetString("ShowSelectedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show common cards.
        /// </summary>
        public static string ShowTradeSugestions {
            get {
                return ResourceManager.GetString("ShowTradeSugestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string StrikethroughText {
            get {
                return ResourceManager.GetString("StrikethroughText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string UnderlineText {
            get {
                return ResourceManager.GetString("UnderlineText", resourceCulture);
            }
        }
    }
}
