//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s32.Sceh.WinApp.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuItems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuItems() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("s32.Sceh.WinApp.Translations.MenuItems", typeof(MenuItems).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Badge page.
        /// </summary>
        public static string BadgePage {
            get {
                return ResourceManager.GetString("BadgePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Badges.
        /// </summary>
        public static string Badges {
            get {
                return ResourceManager.GetString("Badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Change profile.
        /// </summary>
        public static string ChangeProfile {
            get {
                return ResourceManager.GetString("ChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy card _name.
        /// </summary>
        public static string CopyCardName {
            get {
                return ResourceManager.GetString("CopyCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy _game and card name.
        /// </summary>
        public static string CopyGameAndCardName {
            get {
                return ResourceManager.GetString("CopyGameAndCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy game _name.
        /// </summary>
        public static string CopyGameName {
            get {
                return ResourceManager.GetString("CopyGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy _name.
        /// </summary>
        public static string CopyName {
            get {
                return ResourceManager.GetString("CopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect _all cards.
        /// </summary>
        public static string DeselectAllCards {
            get {
                return ResourceManager.GetString("DeselectAllCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect _my cards.
        /// </summary>
        public static string DeselectMyCards {
            get {
                return ResourceManager.GetString("DeselectMyCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect _his cards.
        /// </summary>
        public static string DeselectOtherCards {
            get {
                return ResourceManager.GetString("DeselectOtherCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Notes.
        /// </summary>
        public static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted text.
        /// </summary>
        public static string FormattedText {
            get {
                return ResourceManager.GetString("FormattedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Incoming offers.
        /// </summary>
        public static string IncomingOffers {
            get {
                return ResourceManager.GetString("IncomingOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make offer.
        /// </summary>
        public static string MakeOffer {
            get {
                return ResourceManager.GetString("MakeOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Market page.
        /// </summary>
        public static string MarketPage {
            get {
                return ResourceManager.GetString("MarketPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _My profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open market pages for each selected card.
        /// </summary>
        public static string OpenAllMarketPages {
            get {
                return ResourceManager.GetString("OpenAllMarketPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam _Card Exchange.
        /// </summary>
        public static string OpenSceInvPage {
            get {
                return ResourceManager.GetString("OpenSceInvPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Other profile.
        /// </summary>
        public static string OthersProfile {
            get {
                return ResourceManager.GetString("OthersProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain text.
        /// </summary>
        public static string PlainText {
            get {
                return ResourceManager.GetString("PlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post _history.
        /// </summary>
        public static string PostHistory {
            get {
                return ResourceManager.GetString("PostHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Profile page.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select cards from _offer.
        /// </summary>
        public static string SelectCardsFromOffer {
            get {
                return ResourceManager.GetString("SelectCardsFromOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sent offers.
        /// </summary>
        public static string SentOffers {
            get {
                return ResourceManager.GetString("SentOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sort cards.
        /// </summary>
        public static string SortCards {
            get {
                return ResourceManager.GetString("SortCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By card average price, ascending.
        /// </summary>
        public static string SortCards_ByCardAvgPriceAsc {
            get {
                return ResourceManager.GetString("SortCards_ByCardAvgPriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By card average price, descending.
        /// </summary>
        public static string SortCards_ByCardAvgPriceDesc {
            get {
                return ResourceManager.GetString("SortCards_ByCardAvgPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By surplus of cards, my cards, ascending.
        /// </summary>
        public static string SortCards_ByMyCardsSurplusAsc {
            get {
                return ResourceManager.GetString("SortCards_ByMyCardsSurplusAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By surplus of cards, my cards, descending.
        /// </summary>
        public static string SortCards_ByMyCardsSurplusDesc {
            get {
                return ResourceManager.GetString("SortCards_ByMyCardsSurplusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By set completion rate, my cards, ascending.
        /// </summary>
        public static string SortCards_ByMySetCompletionRateAsc {
            get {
                return ResourceManager.GetString("SortCards_ByMySetCompletionRateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By set completion rate, my cards, descending.
        /// </summary>
        public static string SortCards_ByMySetCompletionRateDesc {
            get {
                return ResourceManager.GetString("SortCards_ByMySetCompletionRateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By name, ascending.
        /// </summary>
        public static string SortCards_ByNameAsc {
            get {
                return ResourceManager.GetString("SortCards_ByNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By name, descending.
        /// </summary>
        public static string SortCards_ByNameDesc {
            get {
                return ResourceManager.GetString("SortCards_ByNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By surplus of cards, other cards, ascending.
        /// </summary>
        public static string SortCards_ByOtherCardsSurplusAsc {
            get {
                return ResourceManager.GetString("SortCards_ByOtherCardsSurplusAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By surplus of cards, other cards, descending.
        /// </summary>
        public static string SortCards_ByOtherCardsSurplusDesc {
            get {
                return ResourceManager.GetString("SortCards_ByOtherCardsSurplusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By set completion rate, other cards, ascending.
        /// </summary>
        public static string SortCards_ByOtherSetCompletionRateAsc {
            get {
                return ResourceManager.GetString("SortCards_ByOtherSetCompletionRateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By set completion rate, other cards, descending.
        /// </summary>
        public static string SortCards_ByOtherSetCompletionRateDesc {
            get {
                return ResourceManager.GetString("SortCards_ByOtherSetCompletionRateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By card SCE worth, ascending.
        /// </summary>
        public static string SortCards_BySceWorthAsc {
            get {
                return ResourceManager.GetString("SortCards_BySceWorthAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By card SCE worth, descending.
        /// </summary>
        public static string SortCards_BySceWorthDesc {
            get {
                return ResourceManager.GetString("SortCards_BySceWorthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By number of cards in set, ascending.
        /// </summary>
        public static string SortCards_ByTotalUniqueCardsAsc {
            get {
                return ResourceManager.GetString("SortCards_ByTotalUniqueCardsAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By number of cards in set.
        /// </summary>
        public static string SortCards_ByTotalUniqueCardsDesc {
            get {
                return ResourceManager.GetString("SortCards_ByTotalUniqueCardsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Store page.
        /// </summary>
        public static string StorePage {
            get {
                return ResourceManager.GetString("StorePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading _topics.
        /// </summary>
        public static string TradeTopics {
            get {
                return ResourceManager.GetString("TradeTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Trade forum.
        /// </summary>
        public static string TradingForum {
            get {
                return ResourceManager.GetString("TradingForum", resourceCulture);
            }
        }
    }
}
