//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s32.Sceh.WinApp.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("s32.Sceh.WinApp.Translations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odznaka Steam.
        /// </summary>
        public static string CardContextMenu_BadgePage {
            get {
                return ResourceManager.GetString("CardContextMenu_BadgePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupno i sprzedaż.
        /// </summary>
        public static string CardContextMenu_MarketPage {
            get {
                return ResourceManager.GetString("CardContextMenu_MarketPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona sklepu.
        /// </summary>
        public static string CardContextMenu_StorePage {
            get {
                return ResourceManager.GetString("CardContextMenu_StorePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum wymiany.
        /// </summary>
        public static string CardContextMenu_TradingForum {
            get {
                return ResourceManager.GetString("CardContextMenu_TradingForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdź.
        /// </summary>
        public static string CheckButtonCommand {
            get {
                return ResourceManager.GetString("CheckButtonCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sprawdź.
        /// </summary>
        public static string CheckButtonText {
            get {
                return ResourceManager.GetString("CheckButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Porównaj.
        /// </summary>
        public static string CompareButtonText {
            get {
                return ResourceManager.GetString("CompareButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podczas ściągania danych profilu wystąpił wyjątek: {0}.
        /// </summary>
        public static string ExceptionDuringDownloadingSteamProfile {
            get {
                return ResourceManager.GetString("ExceptionDuringDownloadingSteamProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędny identyfikator lub własny url profilu.
        /// </summary>
        public static string InvalidProfileIdOrUrl {
            get {
                return ResourceManager.GetString("InvalidProfileIdOrUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zaloguj.
        /// </summary>
        public static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Profil:.
        /// </summary>
        public static string LoginProfileLabel {
            get {
                return ResourceManager.GetString("LoginProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam cards exchange helper.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Odznaki.
        /// </summary>
        public static string MenuItem_Badges {
            get {
                return ResourceManager.GetString("MenuItem_Badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z_mień profil.
        /// </summary>
        public static string MenuItem_ChangeProfile {
            get {
                return ResourceManager.GetString("MenuItem_ChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zakończ.
        /// </summary>
        public static string MenuItem_Exit {
            get {
                return ResourceManager.GetString("MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ekwipunek.
        /// </summary>
        public static string MenuItem_Inventory {
            get {
                return ResourceManager.GetString("MenuItem_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mój _profil.
        /// </summary>
        public static string MenuItem_MyProfile {
            get {
                return ResourceManager.GetString("MenuItem_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugi profil.
        /// </summary>
        public static string MenuItem_OthersProfile {
            get {
                return ResourceManager.GetString("MenuItem_OthersProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można załadować twoich kart: {0}.
        /// </summary>
        public static string OwnerInvErrorMessage {
            get {
                return ResourceManager.GetString("OwnerInvErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd odczytu danych profilu.
        /// </summary>
        public static string ProfileDeserializationError {
            get {
                return ResourceManager.GetString("ProfileDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licznik zapytań: {0}.
        /// </summary>
        public static string RequestCountFormat {
            get {
                return ResourceManager.GetString("RequestCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można załadować kart użytkownika {0}: {1}.
        /// </summary>
        public static string SecondInvErrorMessage {
            get {
                return ResourceManager.GetString("SecondInvErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieznany błąd.
        /// </summary>
        public static string UnknownErrorOccured {
            get {
                return ResourceManager.GetString("UnknownErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono profilu.
        /// </summary>
        public static string WrongProfileIdOrUrl {
            get {
                return ResourceManager.GetString("WrongProfileIdOrUrl", resourceCulture);
            }
        }
    }
}
