//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s32.Sceh.WinApp.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("s32.Sceh.WinApp.Translations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Auto login.
        /// </summary>
        public static string AutoLoginCheckBoxText {
            get {
                return ResourceManager.GetString("AutoLoginCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste date.
        /// </summary>
        public static string Button_PasteDate {
            get {
                return ResourceManager.GetString("Button_PasteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste my selected cards.
        /// </summary>
        public static string Button_PasteMyCards {
            get {
                return ResourceManager.GetString("Button_PasteMyCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste other selected cards.
        /// </summary>
        public static string Button_PasteOtherCards {
            get {
                return ResourceManager.GetString("Button_PasteOtherCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score down -1.
        /// </summary>
        public static string Button_ScoreDown {
            get {
                return ResourceManager.GetString("Button_ScoreDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score up +1.
        /// </summary>
        public static string Button_ScoreUp {
            get {
                return ResourceManager.GetString("Button_ScoreUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Compare.
        /// </summary>
        public static string CompareButtonText {
            get {
                return ResourceManager.GetString("CompareButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while downloading the profile data: {0}.
        /// </summary>
        public static string ExceptionDuringDownloadingSteamProfile {
            get {
                return ResourceManager.GetString("ExceptionDuringDownloadingSteamProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find cards or games.
        /// </summary>
        public static string FindCardsButtonText {
            get {
                return ResourceManager.GetString("FindCardsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images downloading: {0}/{1}/{2}.
        /// </summary>
        public static string ImagesToDownloadFormat {
            get {
                return ResourceManager.GetString("ImagesToDownloadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid id or own profile url.
        /// </summary>
        public static string InvalidProfileIdOrUrl {
            get {
                return ResourceManager.GetString("InvalidProfileIdOrUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided trade URL is invalid.
        /// </summary>
        public static string InvalidTradeUrl {
            get {
                return ResourceManager.GetString("InvalidTradeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided trade URL have to use https scheme.
        /// </summary>
        public static string InvalidTradeUrlScheme {
            get {
                return ResourceManager.GetString("InvalidTradeUrlScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Enter.
        /// </summary>
        public static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Profile:.
        /// </summary>
        public static string LoginProfileLabel {
            get {
                return ResourceManager.GetString("LoginProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam cards exchange helper.
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Badge page.
        /// </summary>
        public static string MenuItem_BadgePage {
            get {
                return ResourceManager.GetString("MenuItem_BadgePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Badges.
        /// </summary>
        public static string MenuItem_Badges {
            get {
                return ResourceManager.GetString("MenuItem_Badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Change profile.
        /// </summary>
        public static string MenuItem_ChangeProfile {
            get {
                return ResourceManager.GetString("MenuItem_ChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy _name.
        /// </summary>
        public static string MenuItem_CopyName {
            get {
                return ResourceManager.GetString("MenuItem_CopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Notes.
        /// </summary>
        public static string MenuItem_EditNote {
            get {
                return ResourceManager.GetString("MenuItem_EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string MenuItem_Exit {
            get {
                return ResourceManager.GetString("MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Incoming offers.
        /// </summary>
        public static string MenuItem_IncomingOffers {
            get {
                return ResourceManager.GetString("MenuItem_IncomingOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Inventory.
        /// </summary>
        public static string MenuItem_Inventory {
            get {
                return ResourceManager.GetString("MenuItem_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make offer.
        /// </summary>
        public static string MenuItem_MakeOffer {
            get {
                return ResourceManager.GetString("MenuItem_MakeOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Market page.
        /// </summary>
        public static string MenuItem_MarketPage {
            get {
                return ResourceManager.GetString("MenuItem_MarketPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _My profile.
        /// </summary>
        public static string MenuItem_MyProfile {
            get {
                return ResourceManager.GetString("MenuItem_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Other profile.
        /// </summary>
        public static string MenuItem_OthersProfile {
            get {
                return ResourceManager.GetString("MenuItem_OthersProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post _history.
        /// </summary>
        public static string MenuItem_PostHistory {
            get {
                return ResourceManager.GetString("MenuItem_PostHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Profile page.
        /// </summary>
        public static string MenuItem_Profile {
            get {
                return ResourceManager.GetString("MenuItem_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sent offers.
        /// </summary>
        public static string MenuItem_SentOffers {
            get {
                return ResourceManager.GetString("MenuItem_SentOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Store page.
        /// </summary>
        public static string MenuItem_StorePage {
            get {
                return ResourceManager.GetString("MenuItem_StorePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading _topics.
        /// </summary>
        public static string MenuItem_TradeTopics {
            get {
                return ResourceManager.GetString("MenuItem_TradeTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Trade forum.
        /// </summary>
        public static string MenuItem_TradingForum {
            get {
                return ResourceManager.GetString("MenuItem_TradingForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NotesButtonText {
            get {
                return ResourceManager.GetString("NotesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string NotesEditorLabel {
            get {
                return ResourceManager.GetString("NotesEditorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string NotesPreviewLabel {
            get {
                return ResourceManager.GetString("NotesPreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load your cards: {0}.
        /// </summary>
        public static string OwnerInvErrorMessage {
            get {
                return ResourceManager.GetString("OwnerInvErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading profile data.
        /// </summary>
        public static string ProfileDeserializationError {
            get {
                return ResourceManager.GetString("ProfileDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request counter: {0}.
        /// </summary>
        public static string RequestCountFormat {
            get {
                return ResourceManager.GetString("RequestCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load cards of user {0}: {1}.
        /// </summary>
        public static string SecondInvErrorMessage {
            get {
                return ResourceManager.GetString("SecondInvErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all cards.
        /// </summary>
        public static string ShowAllButtonText {
            get {
                return ResourceManager.GetString("ShowAllButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show duplicated cards for trade.
        /// </summary>
        public static string ShowDuplicatesButtonText {
            get {
                return ResourceManager.GetString("ShowDuplicatesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my cards.
        /// </summary>
        public static string ShowMyCardsButtonText {
            get {
                return ResourceManager.GetString("ShowMyCardsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only selected cards.
        /// </summary>
        public static string ShowOnlySelectedButtonText {
            get {
                return ResourceManager.GetString("ShowOnlySelectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show his cards.
        /// </summary>
        public static string ShowOtherCardsButtonText {
            get {
                return ResourceManager.GetString("ShowOtherCardsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show selected games.
        /// </summary>
        public static string ShowSelectedAppButtonText {
            get {
                return ResourceManager.GetString("ShowSelectedAppButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show common cards.
        /// </summary>
        public static string ShowTradeSugestionsButtonText {
            get {
                return ResourceManager.GetString("ShowTradeSugestionsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided trade URL doesn&apos;t match the pattern. Are you sure you want to use it?.
        /// </summary>
        public static string StrangeTradeUrl {
            get {
                return ResourceManager.GetString("StrangeTradeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade URL:.
        /// </summary>
        public static string TradeLinkLabel {
            get {
                return ResourceManager.GetString("TradeLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored trade URL seems to be invalid and cannot be used. Please correct the url on user notes screen..
        /// </summary>
        public static string TradeUrlSeemsToBeInvalid {
            get {
                return ResourceManager.GetString("TradeUrlSeemsToBeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred.
        /// </summary>
        public static string UnknownErrorOccured {
            get {
                return ResourceManager.GetString("UnknownErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid trade URL looks like &quot;https://steamcommunity.com/tradeoffer/new/?partner=123456789&amp;token=abcdefgh&quot;.
        /// </summary>
        public static string ValidTradeUrlToolTip {
            get {
                return ResourceManager.GetString("ValidTradeUrlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not found.
        /// </summary>
        public static string WrongProfileIdOrUrl {
            get {
                return ResourceManager.GetString("WrongProfileIdOrUrl", resourceCulture);
            }
        }
    }
}
